CREATE DATABASE ex01

USE ex01

CREATE TABLE Empresa (
	IdEmpresa	INT PRIMARY KEY IDENTITY,
	NomeEmpresa	VARCHAR (200) NOT NULL
);

CREATE TABLE Marcas (
	IdMarca		INT PRIMARY KEY IDENTITY,
	NomeMarca	VARCHAR (200) NOT NULL
);

CREATE TABLE Modelos (
	IdModelo	INT PRIMARY KEY IDENTITY,
	NomeModelo	VARCHAR (200) NOT NULL,
	IdMarca		INT FOREIGN KEY REFERENCES Marcas (IdMarca)
);


CREATE TABLE Veiculos (
	IdVeiculo	INT PRIMARY KEY IDENTITY,
	Placa		VARCHAR (200) NOT NULL UNIQUE,
	IdEmpresa	INT FOREIGN KEY REFERENCES Empresa (IdEmpresa),
	IdModelo	INT FOREIGN KEY REFERENCES Modelos (IdModelo)
	
);

CREATE TABLE Clientes (
	IdCliente	INT PRIMARY KEY IDENTITY,
	NomeCliente	VARCHAR (200) NOT NULL,
	Cpf			VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE Alugueis (
	IdAluguel	INT PRIMARY KEY IDENTITY,
	DataInicio	DATE NOT NULL,
	DataFim 	DATE NOT NULL,
	IdVeiculo	INT FOREIGN KEY REFERENCES Veiculos (IdVeiculo),
	IdCliente	INT FOREIGN KEY REFERENCES Clientes (IdCliente)
);



